"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-07-22 20:23:23.757371+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heatmap_bins',
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.String(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('game_mode', sa.String(length=24), server_default=sa.text("''"), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('map_name', 'kind', 'account_id', 'game_mode', 'day', 'grid_x', 'grid_y')
    )
    op.create_index('ix_heatmap_lookup', 'heatmap_bins', ['map_name', 'kind', 'account_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('shard', sa.String(length=16), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.Column('game_mode', sa.String(length=24), nullable=False),
    sa.Column('match_type', sa.String(length=24), nullable=False),
    sa.Column('is_custom_match', sa.Boolean(), nullable=False),
    sa.Column('season_state', sa.String(length=16), nullable=True),
    sa.Column('title_id', sa.String(length=32), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('telemetry_url', sa.Text(), nullable=True),
    sa.Column('telemetry_key', sa.Text(), nullable=True),
    sa.Column('telemetry_bytes', sa.BigInteger(), nullable=True),
    sa.Column('telemetry_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telemetry_parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_version', sa.Integer(), nullable=True),
    sa.Column('replay_key', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_game_mode'), 'matches', ['game_mode'], unique=False)
    op.create_index(op.f('ix_matches_map_name'), 'matches', ['map_name'], unique=False)
    op.create_index(op.f('ix_matches_match_type'), 'matches', ['match_type'], unique=False)
    op.create_index(op.f('ix_matches_played_at'), 'matches', ['played_at'], unique=False)
    op.create_index(op.f('ix_matches_shard'), 'matches', ['shard'], unique=False)
    op.create_table('players',
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('shard', sa.String(length=16), nullable=False),
    sa.Column('tracked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_error', sa.Text(), nullable=True),
    sa.Column('consecutive_poll_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("account_id LIKE 'account.%'", name='ck_players_human_only'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_tracked'), 'players', ['tracked'], unique=False)
    op.create_table('rosters',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'team_id')
    )
    op.create_index('ix_rosters_match_rank', 'rosters', ['match_id', 'rank'], unique=False)
    op.create_table('participants',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('dbnos', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('boosts', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Float(), nullable=False),
    sa.Column('death_type', sa.String(length=16), nullable=False),
    sa.Column('headshot_kills', sa.Integer(), nullable=False),
    sa.Column('heals', sa.Integer(), nullable=False),
    sa.Column('kill_place', sa.Integer(), nullable=False),
    sa.Column('kill_streaks', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('longest_kill', sa.Float(), nullable=False),
    sa.Column('revives', sa.Integer(), nullable=False),
    sa.Column('ride_distance', sa.Float(), nullable=False),
    sa.Column('road_kills', sa.Integer(), nullable=False),
    sa.Column('swim_distance', sa.Float(), nullable=False),
    sa.Column('team_kills', sa.Integer(), nullable=False),
    sa.Column('time_survived', sa.Float(), nullable=False),
    sa.Column('vehicle_destroys', sa.Integer(), nullable=False),
    sa.Column('walk_distance', sa.Float(), nullable=False),
    sa.Column('weapons_acquired', sa.Integer(), nullable=False),
    sa.Column('win_place', sa.Integer(), nullable=False),
    sa.Column('kills_human', sa.Integer(), nullable=True),
    sa.Column('landing_x', sa.Float(), nullable=True),
    sa.Column('landing_y', sa.Float(), nullable=True),
    sa.Column('landed_at_s', sa.Float(), nullable=True),
    sa.Column('death_x', sa.Float(), nullable=True),
    sa.Column('death_y', sa.Float(), nullable=True),
    sa.Column('died_at_s', sa.Float(), nullable=True),
    sa.Column('killer_account_id', sa.String(length=64), nullable=True),
    sa.Column('death_weapon', sa.String(length=64), nullable=True),
    sa.CheckConstraint('kills >= 0', name='ck_participants_kills_nonneg'),
    sa.ForeignKeyConstraint(['match_id', 'team_id'], ['rosters.match_id', 'rosters.team_id'], name='fk_participants_roster', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'account_id')
    )
    op.create_index('ix_participants_account', 'participants', ['account_id', 'match_id'], unique=False)
    op.create_index('ix_participants_match_team', 'participants', ['match_id', 'team_id'], unique=False)
    # ### end Alembic commands ###

    # -----------------------------------------------------------------------
    # Hand-written: the partial and functional indexes.
    #
    # These are listed in `HAND_MANAGED_INDEXES` in alembic/env.py and are
    # therefore invisible to --autogenerate, which does not compare a partial
    # index's WHERE predicate and reflects expression indexes back in a form
    # that never matches the model. Autogenerate would otherwise either omit
    # them (as it did here) or, worse, emit a plain full index that silently
    # replaces the partial one.
    #
    # `uq_jobs_dedupe_live` is the load-bearing one: it is the *only* thing
    # making enqueue idempotent. Without it `ON CONFLICT DO NOTHING` has no
    # arbiter to infer, and the poller re-enqueues every match it sees on
    # every single cycle, forever.
    #
    # The predicate text here must match `postgresql_where` in db/models.py and
    # `_DEDUPE_INDEX_WHERE` in queue/jobs.py character for character: Postgres
    # only infers a partial unique index when the statement's ON CONFLICT
    # predicate provably implies the index predicate.
    # -----------------------------------------------------------------------
    op.create_index(
        'ix_players_poll_queue', 'players', ['last_polled_at'],
        unique=False, postgresql_where=sa.text('tracked'),
    )
    op.create_index('ix_players_name_lower', 'players', [sa.text('lower(name)')], unique=False)
    op.create_index(
        'ix_matches_official_played_at', 'matches', ['played_at'],
        unique=False, postgresql_where=sa.text("match_type = 'official'"),
    )
    op.create_index(
        'ix_matches_needs_telemetry', 'matches', ['played_at'],
        unique=False, postgresql_where=sa.text('telemetry_key IS NULL'),
    )
    op.create_index(
        'ix_matches_needs_parse', 'matches', ['played_at'],
        unique=False,
        postgresql_where=sa.text('telemetry_key IS NOT NULL AND telemetry_parsed_at IS NULL'),
    )
    op.create_index(
        'ix_participants_human', 'participants', ['account_id'],
        unique=False, postgresql_where=sa.text('NOT is_bot'),
    )
    op.create_index(
        'uq_jobs_dedupe_live', 'jobs', ['dedupe_key'],
        unique=True, postgresql_where=sa.text("state IN ('pending', 'running')"),
    )
    op.create_index(
        'ix_jobs_claim', 'jobs', ['run_after'],
        unique=False, postgresql_where=sa.text("state = 'pending'"),
    )


def downgrade() -> None:
    # Hand-written indexes first — see upgrade().
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_index('uq_jobs_dedupe_live', table_name='jobs')
    op.drop_index('ix_participants_human', table_name='participants')
    op.drop_index('ix_matches_needs_parse', table_name='matches')
    op.drop_index('ix_matches_needs_telemetry', table_name='matches')
    op.drop_index('ix_matches_official_played_at', table_name='matches')
    op.drop_index('ix_players_name_lower', table_name='players')
    op.drop_index('ix_players_poll_queue', table_name='players')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_participants_match_team', table_name='participants')
    op.drop_index('ix_participants_account', table_name='participants')
    op.drop_table('participants')
    op.drop_index('ix_rosters_match_rank', table_name='rosters')
    op.drop_table('rosters')
    op.drop_index(op.f('ix_players_tracked'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_shard'), table_name='matches')
    op.drop_index(op.f('ix_matches_played_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_type'), table_name='matches')
    op.drop_index(op.f('ix_matches_map_name'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_mode'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_heatmap_lookup', table_name='heatmap_bins')
    op.drop_table('heatmap_bins')
    # ### end Alembic commands ###
