"""kill_events and telemetry columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-22 21:44:33.609754+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_events',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_s', sa.Float(), nullable=False),
    sa.Column('victim_account_id', sa.String(length=64), nullable=False),
    sa.Column('victim_team_id', sa.Integer(), nullable=False),
    sa.Column('victim_is_bot', sa.Boolean(), nullable=False),
    sa.Column('victim_x', sa.Float(), nullable=False),
    sa.Column('victim_y', sa.Float(), nullable=False),
    sa.Column('killer_account_id', sa.String(length=64), nullable=True),
    sa.Column('killer_team_id', sa.Integer(), nullable=True),
    sa.Column('killer_is_bot', sa.Boolean(), nullable=True),
    sa.Column('killer_x', sa.Float(), nullable=True),
    sa.Column('killer_y', sa.Float(), nullable=True),
    sa.Column('dbno_maker_account_id', sa.String(length=64), nullable=True),
    sa.Column('finisher_account_id', sa.String(length=64), nullable=True),
    sa.Column('weapon', sa.String(length=64), nullable=True),
    sa.Column('damage_type', sa.String(length=48), nullable=True),
    sa.Column('damage_reason', sa.String(length=24), nullable=True),
    sa.Column('distance_cm', sa.Float(), nullable=True),
    sa.Column('is_suicide', sa.Boolean(), nullable=False),
    sa.Column('is_team_kill', sa.Boolean(), nullable=False),
    sa.Column('through_wall', sa.Boolean(), nullable=True),
    sa.Column('assists', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'seq')
    )
    op.create_index('ix_kill_victim', 'kill_events', ['victim_account_id', 'match_id'], unique=False)
    op.add_column('matches', sa.Column('parse_error', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('replay_bytes', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('heat_ledger_key', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('telemetry_t0', sa.DateTime(timezone=True), nullable=True))
    op.add_column('matches', sa.Column('team_size', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('weather_id', sa.String(length=32), nullable=True))
    op.add_column('matches', sa.Column('camera_view', sa.String(length=16), nullable=True))
    op.add_column('matches', sa.Column('num_start_players', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('num_start_teams', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('bot_count', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('knocks_human', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('shots_fired', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('shots_hit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # -----------------------------------------------------------------------
    # Hand-written: partial indexes, invisible to --autogenerate.
    # See HAND_MANAGED_INDEXES in alembic/env.py and the note in 0001.
    #
    # Both are partial on `killer_account_id IS NOT NULL` because a zone,
    # fall or drown death has no killer at all — 2.9% of rows in the corpus —
    # and neither the "who killed whom" nor the "kills with weapon X" query
    # ever wants them.
    # -----------------------------------------------------------------------
    op.create_index(
        'ix_kill_killer', 'kill_events', ['killer_account_id', 'match_id'],
        unique=False, postgresql_where=sa.text('killer_account_id IS NOT NULL'),
    )
    op.create_index(
        'ix_kill_weapon', 'kill_events', ['weapon'],
        unique=False, postgresql_where=sa.text('killer_account_id IS NOT NULL'),
    )


def downgrade() -> None:
    # Hand-written indexes first — see upgrade().
    op.drop_index('ix_kill_weapon', table_name='kill_events')
    op.drop_index('ix_kill_killer', table_name='kill_events')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'shots_hit')
    op.drop_column('participants', 'shots_fired')
    op.drop_column('participants', 'knocks_human')
    op.drop_column('matches', 'bot_count')
    op.drop_column('matches', 'num_start_teams')
    op.drop_column('matches', 'num_start_players')
    op.drop_column('matches', 'camera_view')
    op.drop_column('matches', 'weather_id')
    op.drop_column('matches', 'team_size')
    op.drop_column('matches', 'telemetry_t0')
    op.drop_column('matches', 'heat_ledger_key')
    op.drop_column('matches', 'replay_bytes')
    op.drop_column('matches', 'parse_error')
    op.drop_index('ix_kill_victim', table_name='kill_events')
    op.drop_table('kill_events')
    # ### end Alembic commands ###
