"""strategy metrics

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-23 16:15:26.108009+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_metrics',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('blue_s', sa.Float(), nullable=True),
    sa.Column('blue_damage', sa.Float(), nullable=True),
    sa.Column('rotate_lag_s', sa.Float(), nullable=True),
    sa.Column('teammate_dist_avg_cm', sa.Float(), nullable=True),
    sa.Column('teammate_near_pct', sa.Float(), nullable=True),
    sa.Column('hot_drop_n', sa.Integer(), nullable=True),
    sa.Column('first_engage_s', sa.Float(), nullable=True),
    sa.Column('dmg_dealt_early', sa.Float(), nullable=True),
    sa.Column('dmg_taken_early', sa.Float(), nullable=True),
    sa.Column('first_weapon_s', sa.Float(), nullable=True),
    sa.Column('early_pickups_n', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'account_id')
    )
    op.create_index('ix_strategy_account', 'strategy_metrics', ['account_id', 'match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_account', table_name='strategy_metrics')
    op.drop_table('strategy_metrics')
    # ### end Alembic commands ###
