"""derived accuracy and per-weapon stats

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-28 22:12:51.180207+00:00

**`participants.shots_fired` and `shots_hit` change meaning here.** They used
to hold PUBG's `allWeaponStats` figures, which exist for a median of two
accounts per match; from parser v10 they are derived from `LogPlayerAttack`
and exist for ~90% of human participants. PUBG's own numbers move to the new
`aws_shots`/`aws_hits`, where a corpus test keeps comparing the two.

No backfill: the values are re-derived by the reparse that the parser version
bump requires, and there is nothing to compute here that the parser does not
compute better. The new columns are nullable so a row parsed by an older
version reads as "unknown" rather than as a confident zero.

`participant_weapons` is delete-then-insert on `match_id` and writes nothing
to `heatmap_bins`, so the heat ledger is untouched by this migration.

The one index here is plain, not partial, so autogenerate emits it correctly
and nothing needs adding to `HAND_MANAGED_INDEXES`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant_weapons',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('weapon', sa.String(length=64), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('shots_landed', sa.Integer(), nullable=False),
    sa.Column('hit_events', sa.Integer(), nullable=False),
    sa.Column('dbno_hit_events', sa.Integer(), nullable=False),
    sa.Column('headshot_events', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'account_id', 'weapon')
    )
    op.create_index('ix_participant_weapons_account', 'participant_weapons', ['account_id', 'weapon'], unique=False)
    op.add_column('participants', sa.Column('hit_events', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('shots_unknown_weapon', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('aws_shots', sa.Integer(), nullable=True))
    op.add_column('participants', sa.Column('aws_hits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'aws_hits')
    op.drop_column('participants', 'aws_shots')
    op.drop_column('participants', 'shots_unknown_weapon')
    op.drop_column('participants', 'hit_events')
    op.drop_index('ix_participant_weapons_account', table_name='participant_weapons')
    op.drop_table('participant_weapons')
    # ### end Alembic commands ###
