"""knock events and telemetry damage totals

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-28 22:39:28.935462+00:00

`knock_events` answers the half of a squad fight `kill_events` cannot: 51% of
kill victims are still flagged `isDBNO` at the moment of death, so the kill row
credits whoever finished someone rather than whoever won the engagement.

Delete-then-insert on `match_id`, like `kill_events` and `strategy_metrics`.
Nothing here writes to `heatmap_bins`, so the heat ledger is untouched.

**`ix_knock_attacker` is hand-written below and is not in the autogenerate
output above.** It is partial (`WHERE attacker_account_id IS NOT NULL`),
Alembic does not compare a partial index's WHERE predicate, and autogenerate
would otherwise emit a plain full index that silently replaces it. It is
registered in `HAND_MANAGED_INDEXES` in `alembic/env.py` for that reason,
mirroring `ix_kill_killer`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knock_events',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_s', sa.Float(), nullable=False),
    sa.Column('victim_account_id', sa.String(length=64), nullable=False),
    sa.Column('victim_team_id', sa.Integer(), nullable=False),
    sa.Column('victim_is_bot', sa.Boolean(), nullable=False),
    sa.Column('victim_x', sa.Float(), nullable=False),
    sa.Column('victim_y', sa.Float(), nullable=False),
    sa.Column('attacker_account_id', sa.String(length=64), nullable=True),
    sa.Column('attacker_team_id', sa.Integer(), nullable=True),
    sa.Column('attacker_is_bot', sa.Boolean(), nullable=True),
    sa.Column('weapon', sa.String(length=64), nullable=True),
    sa.Column('damage_reason', sa.String(length=24), nullable=True),
    sa.Column('distance_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'seq')
    )
    op.create_index('ix_knock_victim', 'knock_events', ['victim_account_id', 'match_id'], unique=False)
    op.add_column('participants', sa.Column('damage_dealt_telemetry', sa.Float(), nullable=True))
    op.add_column('participants', sa.Column('blue_zone_damage', sa.Float(), nullable=True))
    op.add_column('participants', sa.Column('longest_kill_cm', sa.Float(), nullable=True))
    op.add_column('participants', sa.Column('revives_telemetry', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Hand-managed partial index — see the module docstring. Autogenerate will
    # never emit this; it must be maintained here.
    op.execute(
        "CREATE INDEX ix_knock_attacker ON knock_events "
        "(attacker_account_id, match_id) WHERE attacker_account_id IS NOT NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_knock_attacker")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'revives_telemetry')
    op.drop_column('participants', 'longest_kill_cm')
    op.drop_column('participants', 'blue_zone_damage')
    op.drop_column('participants', 'damage_dealt_telemetry')
    op.drop_index('ix_knock_victim', table_name='knock_events')
    op.drop_table('knock_events')
    # ### end Alembic commands ###
