"""ops alerts and heartbeats

Revision ID: 0008
Revises: 0007
**`uq_ops_alerts_open` is hand-written below and absent from the autogenerate
output.** It is a partial UNIQUE (`WHERE resolved_at IS NULL`); Alembic does not
compare a partial index's WHERE predicate, so autogenerate would emit a plain
`UNIQUE (kind)` that silently forbids ever recording a second incident of the
same kind. Registered in `HAND_MANAGED_INDEXES` in `alembic/env.py`.

Any `ON CONFLICT` against it must spell the predicate `WHERE resolved_at IS NULL`
character for character, or Postgres will not infer the index.

Create Date: 2026-07-28 23:20:19.227072+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('observations', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ops_heartbeats',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###

    # Hand-managed partial UNIQUE — see the module docstring.
    op.execute(
        "CREATE UNIQUE INDEX uq_ops_alerts_open ON ops_alerts (kind) "
        "WHERE resolved_at IS NULL"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS uq_ops_alerts_open")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ops_heartbeats')
    op.drop_table('ops_alerts')
    # ### end Alembic commands ###
