"""engagements

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-29 14:38:50.714348+00:00

Fights, in SQL: one row per exchange of fire between two teams, plus one row
per account that dealt or took a blow in it.

**These two tables hold the parser's only modelled quantity.** Every other
derived table records something PUBG states — a kill, a knock, a circle roster.
An "engagement" is a grouping this codebase invents, cut at a 20 s silence
between the same two teams, and the sweep behind that number found no knee
anywhere from 5 s to 120 s. The per-side counters are facts given the grouping;
the row count is a choice. `telemetry/engagements.py` carries the evidence and
the API hands the constant to the page so it can say so.

There is deliberately **no `outcome` column**. A stored "lost" would outlive
the reasoning behind it, and a fight where we killed two and lost three to a
third party is not obviously ours to have lost. The API derives a label at
query time and names it after what it counts.

`engagement_participants` has an FK to `matches` only, **not** to
`engagements` — nothing would cascade from a shortened reparse, so
`ingest/persist.py` deletes the children first by hand. `seq` is stable only
within a parser version, so a parse producing fewer engagements than the last
would otherwise leave participant rows pointing at a `seq` that now means a
different fight.

Delete-then-insert on `match_id`, like `kill_events`, `knock_events`,
`strategy_metrics`, `participant_weapons` and `zone_play`. Nothing here writes
to `heatmap_bins`, so **the heat ledger is untouched**.

Both indexes are plain B-trees with no WHERE predicate, so — unlike
`ix_kill_killer` — neither is hand-written and neither belongs in
`HAND_MANAGED_INDEXES`. Autogenerate compares them correctly.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_participants',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('hits_dealt', sa.Integer(), nullable=False),
    sa.Column('hits_taken', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Float(), nullable=False),
    sa.Column('damage_taken', sa.Float(), nullable=False),
    sa.Column('knocks', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('was_knocked', sa.Boolean(), nullable=False),
    sa.Column('died', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'seq', 'account_id')
    )
    op.create_index('ix_engagement_participants_account', 'engagement_participants', ['account_id', 'match_id'], unique=False)
    op.create_table('engagements',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('t_start_s', sa.Float(), nullable=False),
    sa.Column('t_end_s', sa.Float(), nullable=False),
    sa.Column('team_a', sa.Integer(), nullable=False),
    sa.Column('team_b', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('first_hit_account_id', sa.String(length=64), nullable=True),
    sa.Column('first_hit_team_id', sa.Integer(), nullable=True),
    sa.Column('first_hit_range_cm', sa.Float(), nullable=True),
    sa.Column('min_range_cm', sa.Float(), nullable=True),
    sa.Column('hits_a', sa.Integer(), nullable=False),
    sa.Column('hits_b', sa.Integer(), nullable=False),
    sa.Column('dmg_a_to_b', sa.Float(), nullable=False),
    sa.Column('dmg_b_to_a', sa.Float(), nullable=False),
    sa.Column('knocks_a', sa.Integer(), nullable=False),
    sa.Column('knocks_b', sa.Integer(), nullable=False),
    sa.Column('kills_a', sa.Integer(), nullable=False),
    sa.Column('kills_b', sa.Integer(), nullable=False),
    sa.Column('third_party_team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'seq')
    )
    op.create_index('ix_engagements_start', 'engagements', ['match_id', 't_start_s'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_engagements_start', table_name='engagements')
    op.drop_table('engagements')
    op.drop_index('ix_engagement_participants_account', table_name='engagement_participants')
    op.drop_table('engagement_participants')
    # ### end Alembic commands ###
