"""death context on kill_events

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-29 15:24:48.088299+00:00

The victim's context at the instant they died, from `telemetry/deaths.py`.

Columns on `kill_events` rather than a table of their own: they describe the
same event the row already describes — `victim_x`/`victim_y` are the precedent
— and a 1:1 table on the same primary key would be a join for nothing.

**Only what SQL cannot already answer.** "Third-partied" joins `engagements`,
"started as a knock" reads `dbno_maker_account_id`, "outside the last circle"
reads `zone_play`. Copying any of those in would go stale the next time the
parser changed, while the join would not. What is left is the position track:
how far the nearest **living** teammate was, and how many were still up.

All five are **nullable**, and that is load-bearing on two of them.
`victim_nearest_teammate_cm` is NULL when nobody was left to be near — 65% of
all deaths measured, which is every solo match plus the last member of every
squad — and that is a different answer from "they were a long way off". A NOT
NULL column with a zero default would make the two indistinguishable, which is
the `allWeaponStats` failure exactly.

No backfill and no index. `kill_events` is delete-then-insert per match, so a
reparse at v17 fills every row; until then the columns read NULL, which is
correct rather than wrong. Nothing here touches `heatmap_bins`, so **the heat
ledger is untouched**.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kill_events', sa.Column('victim_nearest_teammate_cm', sa.Float(), nullable=True))
    op.add_column('kill_events', sa.Column('victim_teammates_alive', sa.Integer(), nullable=True))
    op.add_column('kill_events', sa.Column('victim_in_vehicle', sa.Boolean(), nullable=True))
    op.add_column('kill_events', sa.Column('victim_parachuting', sa.Boolean(), nullable=True))
    op.add_column('kill_events', sa.Column('victim_sample_lag_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kill_events', 'victim_sample_lag_ms')
    op.drop_column('kill_events', 'victim_parachuting')
    op.drop_column('kill_events', 'victim_in_vehicle')
    op.drop_column('kill_events', 'victim_teammates_alive')
    op.drop_column('kill_events', 'victim_nearest_teammate_cm')
    # ### end Alembic commands ###
