"""drop victim_parachuting

`kill_events.victim_parachuting` was added in 0011 and is wrong. It came from
`FrameIndex`'s `FLAG_PARACHUTING`, whose name reads as a per-player state and
is not one: it is set from `common.isGame` being the plane-phase value, which
is a property of the **match**. It is therefore true for the whole lobby at
once, and stays true for anyone who dropped early and is already looting or
fighting on the ground.

Measured over 1,918 archived deaths: 62 carried the flag and **42 of them had
already landed**. The review page rendered "still in the air" beside deaths
that were 4-metre firefights with 96 damage dealt.

Measured properly — against each victim's own `LogParachuteLanding` — exactly
**one** death in the corpus happened while airborne, and that one was a
flare-gun redeploy at 364 s. That is far below the bar that made "died in a
vehicle" a footnote count at 1.0%, so the column is **dropped rather than
corrected**: a column true on one row in two thousand earns nothing.

`FLAG_PARACHUTING` itself stays. `strategy.py` uses it correctly, excluding
plane-phase samples from teammate spread, where the question really is about
the match phase — everyone is bunched inside one aircraft. Its docstring now
says which question it answers.

Irreversible in the sense that matters: `downgrade()` restores the column but
not its data, and a reparse at v19 would leave it NULL. That is the right
outcome — the values were wrong.

Revision ID: 0012
Revises: 0011
Create Date: 2026-07-29 16:42:22.074516+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kill_events', 'victim_parachuting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kill_events', sa.Column('victim_parachuting', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
